(() => {
  if (!matchMedia('(max-width: 767px)').matches) return;
  const YANDEX='https://yandex.ru/navi/org/stluxe/51087098664?si=4x8mkunbkhugdwe7bkyfw55fh0';
  const PHONE='+79163552222';
  const photos=[
    ['assets/images/salon-reception.webp','interior','Интерьер STLuxe'],
    ['assets/images/salon-nail-zone.webp','interior','Рабочая зона STLuxe'],
    ['assets/images/nails-pink.webp','nails','Маникюр STLuxe'],
    ['assets/images/nails-green.webp','nails','Дизайн ногтей STLuxe'],
    ['assets/images/nails-light.webp','nails','Маникюр STLuxe'],
    ['assets/images/hair-style.webp','hair','Работа с волосами STLuxe']
  ];
  const services=[
    ['nails','Маникюр с покрытием гель-лака OPI, Luxio, EMI','1 700 ₽',''],
    ['nails','Женский педикюр — аппаратный, обрезной или комбинированный','2 000 ₽',''],
    ['nails','Экспресс-педикюр — аппаратный, обрезной или комбинированный','1 500 ₽',''],
    ['nails','Наращивание ногтей гелем + цветное верхнее покрытие','3 000 ₽',''],
    ['hair','Стрижка и укладка — короткие волосы до 12 см','800 ₽',''],
    ['hair','Утюжок — доплата при укладке, короткие волосы','300 ₽',''],
    ['hair','Диффузор — доплата при укладке, короткие волосы','150 ₽',''],
    ['hair','Вечерняя причёска — короткие волосы до 12 см','1 500 ₽',''],
    ['hair','Вечерняя причёска — средние волосы до 30 см','1 500 ₽',''],
    ['hair','Вечерняя причёска — длинные волосы от 31 см','1 500 ₽',''],
    ['hair','Биохимическая завивка Selective — короткие волосы','2 000 ₽',''],
    ['hair','Биохимическая завивка Selective — средние волосы','2 400 ₽',''],
    ['hair','Биохимическая завивка Selective — длинные волосы','2 900 ₽',''],
    ['hair','Колорирование / шатуш / балаяж Londa / Barex — короткие волосы','3 400 ₽',''],
    ['hair','Колорирование / шатуш / балаяж Londa / Barex — средние волосы','3 800 ₽',''],
    ['hair','Колорирование / шатуш / балаяж Londa / Barex — длинные волосы','4 500 ₽',''],
    ['hair','Частичное мелирование до 10 прядей при окрашивании — короткие волосы','700 ₽',''],
    ['hair','Частичное мелирование до 10 прядей при окрашивании — длинные волосы','1 500 ₽',''],
    ['hair','Мелирование на фольге и тонирование Londa / Barex — длинные волосы','3 900 ₽',''],
    ['face','Чистка лица','Цена по записи',''],
    ['face','Аппаратная чистка лица','Цена по записи',''],
    ['face','Гальваническая чистка лица','Цена по записи',''],
    ['face','Пилинг лица','Цена по записи',''],
    ['face','Химический пилинг лица','Цена по записи',''],
    ['face','Гликолевый пилинг','Цена по записи',''],
    ['face','Салициловый пилинг','Цена по записи',''],
    ['brows','Коррекция и окрашивание бровей','Цена по записи',''],
    ['lashes','Окрашивание ресниц','Цена по записи',''],
    ['lashes','Наращивание ресниц','Цена по записи',''],
    ['lashes','Голливудское наращивание ресниц','Цена по записи',''],
    ['other','Перманентный макияж','Цена по записи',''],
    ['depilation','Шугаринг','Цена по записи',''],
    ['depilation','Восковая депиляция','Цена по записи',''],
    ['depilation','Эпиляция','Цена по записи','']
  ];
  const reviews=[
    ['мария н.','«Атмосфера в салоне благоприятная, красиво, стильно, уютно… Татьяна — мастер своего дела.»'],
    ['Ольга К.','«Отличная атмосфера, всё чисто, стерильно, приветливый персонал, всегда предлагают чай или кофе.»'],
    ['Елизавета С.','«Отличное обслуживание, все мастера вежливые и отлично выполняют бьюти-услуги! Салон чистый, стильный!»'],
    ['Мама Рита','«Прекрасный косметолог Мария. Умеет всё. Препараты качественные, новейшие. Очень советую мастера.»']
  ];

  const css=document.createElement('style');
  css.textContent=`@import url('https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;450;500&display=swap');
  @media(max-width:767px){
    html,body{margin:0!important;background:#fff!important;color:#0b0b0c!important;font-family:'Inter Tight','Helvetica Neue',Arial,sans-serif!important;font-weight:400!important;-webkit-font-smoothing:antialiased!important;overflow-x:hidden!important}
    body>*:not(#stluxe-luxe-v2):not(script):not(style){display:none!important}#stluxe-luxe-v2{display:block!important}#stluxe-luxe-v2 *{box-sizing:border-box}button,a{font:inherit}.lx{background:#fff;padding-bottom:104px}.lx-pad{padding-left:17px;padding-right:17px}
    .lx-top{height:48px;padding:0 17px;display:flex;align-items:center;justify-content:space-between;background:#fff}.lx-logo{font-size:21px;letter-spacing:-.045em;font-weight:500;text-decoration:none}.lx-map{display:flex;align-items:center;gap:5px;font-size:12px;text-decoration:none;border-bottom:1px solid #111;padding-bottom:2px}.lx-map svg{width:13px;height:13px;stroke:#111;fill:none;stroke-width:1.45}
    .lx-hero-gallery{width:100vw;height:min(70vw,315px);position:relative;overflow:hidden;background:#eee}.lx-track{height:100%;display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none}.lx-track::-webkit-scrollbar{display:none}.lx-slide{min-width:100%;height:100%;scroll-snap-align:start;border:0;padding:0;background:#eee}.lx-slide img{width:100%;height:100%;object-fit:cover;display:block}.lx-counter{position:absolute;right:13px;bottom:32px;height:21px;min-width:34px;padding:0 8px;border-radius:10px;background:rgba(12,12,12,.54);backdrop-filter:blur(8px);color:#fff;font-size:9.5px;letter-spacing:.03em;display:grid;place-items:center}
    .lx-hero{position:relative;z-index:3;margin-top:-20px;background:#fff;border-radius:22px 22px 0 0;padding:22px 17px 20px}.lx-title{font-size:32px;line-height:1.02;letter-spacing:-.052em;font-weight:500;margin:0 0 8px}.lx-sub{font-size:15px;line-height:1.35;color:#555;margin:0 0 12px}.lx-rating{display:flex;align-items:center;gap:7px;font-size:15px;margin-bottom:12px}.lx-rating svg{width:15px;height:15px;fill:#111}.lx-hours{display:flex;align-items:center;gap:7px;font-size:14px;margin-bottom:13px}.lx-hours svg{width:16px;height:16px;stroke:#111;fill:none;stroke-width:1.45}.lx-state{font-weight:500}.lx-state.open{color:#16833d}.lx-state.closed{color:#dd6b20}.lx-address{display:flex;align-items:center;gap:8px;background:#f4f4f4;border-radius:14px;padding:10px 11px;font-size:11.5px;color:#525252;margin-bottom:16px}.lx-address svg{width:16px;height:16px;stroke:#111;fill:none;stroke-width:1.4;flex:0 0 auto}.lx-actions{display:flex;align-items:center;justify-content:space-between;gap:16px}.lx-worklink{display:flex;align-items:center;gap:6px;border:0;background:none;padding:0;font-size:11.5px;color:#222}.lx-worklink svg{width:14px;height:14px;stroke:#111;fill:none;stroke-width:1.4}.lx-book{border:0;background:#111;color:#fff!important;border-radius:999px;height:44px;padding:0 22px;font-size:12px;font-weight:500}
    .lx-nav{height:47px;position:sticky;top:0;z-index:40;background:rgba(255,255,255,.97);backdrop-filter:blur(16px);border-top:1px solid #ededed;border-bottom:1px solid #e8e8e8;display:flex;align-items:center;overflow-x:auto;scrollbar-width:none;padding:0 11px}.lx-nav::-webkit-scrollbar{display:none}.lx-nav button{border:0;background:none;padding:0 11px;height:100%;white-space:nowrap;font-size:10.5px;color:#777}.lx-nav button.active{color:#111;font-weight:500}
    .lx-section{padding:27px 17px 30px;scroll-margin-top:48px}.lx-break{border-top:8px solid #f4f4f4}.lx-head{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin-bottom:15px}.lx-head h2{font-size:24px;line-height:1.05;letter-spacing:-.043em;font-weight:500;margin:0}.lx-head p{font-size:11.5px;line-height:1.45;color:#777;margin:5px 0 0}.lx-all{border:0;background:none;border-bottom:1px solid #111;padding:0 0 2px;font-size:10.5px;white-space:nowrap}
    .lx-filters{display:flex;gap:7px;overflow-x:auto;scrollbar-width:none;margin:0 -17px 14px;padding:0 17px}.lx-filters::-webkit-scrollbar{display:none}.lx-filter{border:1px solid #dedede;background:#fff;border-radius:999px;padding:7px 11px;font-size:10px;white-space:nowrap;color:#666}.lx-filter.active{background:#111;border-color:#111;color:#fff}.lx-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.lx-photo{border:0;padding:0;border-radius:13px;overflow:hidden;aspect-ratio:1/1.16;background:#eee}.lx-photo img{width:100%;height:100%;object-fit:cover}.lx-photo[hidden]{display:none}.lx-open-gallery{width:100%;height:42px;margin-top:11px;border:1px solid #d9d9d9;border-radius:999px;background:#fff;font-size:11px}
    .lx-tabs{display:flex;gap:7px;overflow-x:auto;scrollbar-width:none;margin:0 -17px 15px;padding:0 17px}.lx-tabs::-webkit-scrollbar{display:none}.lx-tabs button{border:1px solid #e0e0e0;background:#fff;border-radius:999px;padding:7px 11px;font-size:10px;white-space:nowrap;color:#666}.lx-tabs button.active{background:#111;color:#fff;border-color:#111}.lx-services{display:grid;gap:9px}.lx-service{border:1px solid #e6e6e6;border-radius:16px;background:#fff;padding:14px;box-shadow:0 4px 18px rgba(0,0,0,.025)}.lx-sname{font-size:13.5px;line-height:1.38;color:#161616;margin-bottom:12px}.lx-smeta{display:flex;align-items:flex-end;justify-content:space-between;gap:12px}.lx-sprice{font-size:12px;color:#555}.lx-duration{display:block;font-size:10px;color:#8a8a8a;margin-top:3px}.lx-reserve{border:0;background:#111;color:#fff!important;border-radius:999px;height:34px;padding:0 13px;font-size:10px}.lx-more{width:100%;height:42px;border:1px solid #d9d9d9;border-radius:999px;background:#fff;margin-top:11px;font-size:11px}
    .lx-teamrow{display:flex;gap:10px;overflow-x:auto;scrollbar-width:none;margin:0 -17px;padding:0 17px 3px}.lx-teamrow::-webkit-scrollbar{display:none}.lx-person{min-width:142px;width:142px;border:0;background:none;padding:0;text-align:left}.lx-personpic{height:178px;border-radius:15px;overflow:hidden;background:linear-gradient(145deg,#e8e8e8,#f5f5f5);position:relative;display:flex;align-items:flex-end;justify-content:center}.lx-personpic svg{width:72px;height:72px;fill:#c5c5c5;margin-bottom:38px}.lx-badge{position:absolute;left:8px;top:8px;background:rgba(255,255,255,.92);border-radius:999px;padding:5px 7px;font-size:9px;color:#333}.lx-pname{font-size:12.5px;margin-top:8px}.lx-prole{font-size:10px;color:#777;margin-top:2px;line-height:1.35}
    .lx-reviews{display:flex;gap:10px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;margin:0 -17px;padding:0 17px 3px}.lx-reviews::-webkit-scrollbar{display:none}.lx-review{min-width:88%;scroll-snap-align:start;border:1px solid #e6e6e6;border-radius:16px;padding:15px;background:#fff}.lx-rhead{display:flex;justify-content:space-between;gap:12px;font-size:11px;margin-bottom:10px}.lx-stars{letter-spacing:1px}.lx-rtext{font-size:12.5px;line-height:1.55;color:#444;margin:0}.lx-yreviews{display:inline-flex;margin-top:14px;font-size:10.5px;border-bottom:1px solid #111;text-decoration:none;padding-bottom:2px}
    .lx-aboutbox{font-size:13px;line-height:1.65;color:#474747}.lx-aboutbox p{margin:0 0 12px}.lx-facts{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:17px}.lx-fact{background:#f4f4f4;border-radius:14px;padding:13px}.lx-fact strong{display:block;font-size:16px;font-weight:500}.lx-fact span{display:block;font-size:10px;color:#777;margin-top:3px}
    .lx-visitcard{border-radius:18px;background:#f5f5f5;padding:15px}.lx-vrow{display:flex;gap:10px;padding:11px 0;border-bottom:1px solid #dedede}.lx-vrow:last-child{border-bottom:0}.lx-vrow svg{width:17px;height:17px;stroke:#111;fill:none;stroke-width:1.4;flex:0 0 auto}.lx-vrow strong{font-size:11.5px;font-weight:500;display:block;margin-bottom:3px}.lx-vrow span{font-size:10.5px;color:#727272;line-height:1.4}.lx-vactions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:11px}.lx-vbtn{height:40px;border-radius:999px;border:1px solid #d6d6d6;background:#fff;font-size:10.5px;display:grid;place-items:center;text-decoration:none}.lx-vbtn.black{background:#111;color:#fff!important;border-color:#111}
    .lx-footer{padding:25px 17px 105px;text-align:center;color:#888;font-size:9.5px}.lx-footer strong{display:block;color:#222;font-size:12px;font-weight:500;margin-bottom:4px}
    .lx-bookbar{position:fixed;left:10px;right:10px;bottom:max(10px,env(safe-area-inset-bottom));z-index:60;height:60px;border:1px solid #e5e5e5;background:rgba(255,255,255,.96);backdrop-filter:blur(18px);border-radius:18px;box-shadow:0 12px 35px rgba(0,0,0,.14);display:flex;align-items:center;justify-content:space-between;padding:7px 7px 7px 13px;opacity:0;transform:translateY(82px);pointer-events:none;transition:.28s ease}.lx-bookbar.show{opacity:1;transform:none;pointer-events:auto}.lx-bookcopy strong{display:block;font-size:10.5px;font-weight:500}.lx-bookcopy span{display:block;font-size:9px;color:#888;margin-top:2px}.lx-bookbar button{height:45px;border:0;border-radius:999px;background:#111;color:#fff!important;padding:0 19px;font-size:10.5px}
    .lx-light{position:fixed;inset:0;z-index:110;background:#050505;display:none;flex-direction:column}.lx-light.open{display:flex}.lx-lighttop{height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 15px;color:#fff}.lx-lighttitle{font-size:11px}.lx-close{width:38px;height:38px;border:1px solid #555;border-radius:50%;background:#111;color:#fff!important;font-size:19px}.lx-lighttrack{flex:1;display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none}.lx-lighttrack::-webkit-scrollbar{display:none}.lx-lightslide{min-width:100%;scroll-snap-align:start;display:flex;align-items:center;justify-content:center}.lx-lightslide img{width:100%;max-height:82vh;object-fit:contain}.lx-lightcount{text-align:center;color:#aaa;font-size:10px;padding:12px 0 max(16px,env(safe-area-inset-bottom))}
  }
  @media(min-width:768px){#stluxe-luxe-v2{display:none!important}}`;
  document.head.appendChild(css);

  const root=document.createElement('div');root.id='stluxe-luxe-v2';
  root.innerHTML=`<main class="lx">
    <header class="lx-top" id="lx-top"><a class="lx-logo" href="#lx-top">STLuxe</a><a class="lx-map" href="${YANDEX}" target="_blank">Яндекс Карты <svg viewBox="0 0 24 24"><path d="M7 17 17 7M9 7h8v8"/></svg></a></header>
    <section class="lx-hero-gallery"><div class="lx-track" id="lxTrack">${photos.map((p,i)=>`<button class="lx-slide" data-i="${i}"><img src="${p[0]}" alt="${p[2]}"></button>`).join('')}</div><div class="lx-counter" id="lxCount">1/6</div></section>
    <section class="lx-hero" id="lxHero"><h1 class="lx-title">STLuxe</h1><p class="lx-sub">Салон красоты · волосы, ногти, косметология и бьюти-услуги</p><div class="lx-rating"><svg viewBox="0 0 24 24"><path d="m12 2.8 2.85 5.77 6.37.93-4.61 4.49 1.09 6.34L12 17.33l-5.7 3 1.09-6.34L2.78 9.5l6.37-.93L12 2.8Z"/></svg><span>4,9 <span style="color:#777">(86 отзывов)</span></span></div><div class="lx-hours"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/></svg><span class="lx-state" id="lxState">Проверяем</span><span id="lxHoursText">— 10:00–20:00</span></div><div class="lx-address"><svg viewBox="0 0 24 24"><path d="M12 21s6-5.4 6-11a6 6 0 1 0-12 0c0 5.6 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></svg><span>Ивантеевка, ул. Победы, 16</span></div><div class="lx-actions"><button class="lx-worklink" id="lxToWorks">Посмотреть работы <svg viewBox="0 0 24 24"><path d="m7 10 5 5 5-5"/></svg></button><button class="lx-book" data-book>Записаться</button></div></section>
    <nav class="lx-nav" id="lxNav"><button data-go="lx-portfolio" class="active">Фото</button><button data-go="lx-services">Услуги</button><button data-go="lx-team">Специалисты</button><button data-go="lx-reviews">Отзывы</button><button data-go="lx-about">О салоне</button><button data-go="lx-visit">Визит</button></nav>
    <section class="lx-section" id="lx-portfolio"><div class="lx-head"><div><h2>Портфолио</h2><p>Работы и пространство STLuxe</p></div></div><div class="lx-filters" id="lxFilters"><button class="lx-filter active" data-cat="all">Все работы</button><button class="lx-filter" data-cat="nails">Ногти</button><button class="lx-filter" data-cat="hair">Волосы</button><button class="lx-filter" data-cat="interior">Салон</button></div><div class="lx-grid" id="lxGrid">${photos.slice(0,4).map((p,i)=>`<button class="lx-photo" data-cat="${p[1]}" data-i="${i}"><img src="${p[0]}" alt="${p[2]}"></button>`).join('')}</div><button class="lx-open-gallery" id="lxOpenGallery">Открыть галерею</button></section>
    <section class="lx-section lx-break" id="lx-services"><div class="lx-head"><div><h2>Услуги</h2><p>Прайс STLuxe — показываем компактно, без длинной простыни</p></div></div><div class="lx-tabs" id="lxTabs"><button class="active" data-scat="all">Все</button><button data-scat="nails">Ногти</button><button data-scat="hair">Волосы</button><button data-scat="face">Косметология</button><button data-scat="brows">Брови</button><button data-scat="lashes">Ресницы</button><button data-scat="depilation">Депиляция</button></div><div class="lx-services" id="lxServices"></div><button class="lx-more" id="lxMore">Посмотреть ещё</button></section>
    <section class="lx-section lx-break" id="lx-team"><div class="lx-head"><div><h2>Специалисты</h2><p>Персональные профили заполним после подтверждения состава команды</p></div></div><div class="lx-teamrow"><button class="lx-person"><div class="lx-personpic"><span class="lx-badge">★ —</span><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M5 21c.5-4.3 2.8-6.5 7-6.5s6.5 2.2 7 6.5Z"/></svg></div><div class="lx-pname">Татьяна</div><div class="lx-prole">Мастер широкого профиля · владелец салона</div></button><button class="lx-person"><div class="lx-personpic"><span class="lx-badge">★ —</span><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M5 21c.5-4.3 2.8-6.5 7-6.5s6.5 2.2 7 6.5Z"/></svg></div><div class="lx-pname">Алёна</div><div class="lx-prole">Мастер STLuxe · профиль дополняется</div></button><button class="lx-person"><div class="lx-personpic"><span class="lx-badge">★ —</span><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M5 21c.5-4.3 2.8-6.5 7-6.5s6.5 2.2 7 6.5Z"/></svg></div><div class="lx-pname">Мария</div><div class="lx-prole">Косметолог · профиль дополняется</div></button></div></section>
    <section class="lx-section lx-break" id="lx-reviews"><div class="lx-head"><div><h2>Отзывы</h2><p>4,9 · 86 отзывов на Яндекс Картах</p></div></div><div class="lx-reviews">${reviews.map(r=>`<article class="lx-review"><div class="lx-rhead"><span>${r[0]}</span><span class="lx-stars">★★★★★</span></div><p class="lx-rtext">${r[1]}</p></article>`).join('')}</div><a class="lx-yreviews" href="${YANDEX}" target="_blank">Все отзывы на Яндекс Картах</a></section>
    <section class="lx-section lx-break" id="lx-about"><div class="lx-head"><div><h2>О салоне</h2><p>STLuxe · Ивантеевка</p></div></div><div class="lx-aboutbox"><p>STLuxe — салон, где в одном месте собраны услуги для волос, ногтей, бровей, ресниц и косметологии. По отзывам гостей, сюда возвращаются за аккуратной работой, чистотой и спокойной атмосферой.</p><p>В салоне отмечают внимательное отношение к пожеланиям, качественные материалы, чай и кофе для гостей, удобное оборудование и возможность прийти всей семьёй.</p><div class="lx-facts"><div class="lx-fact"><strong>4,9</strong><span>рейтинг Яндекса</span></div><div class="lx-fact"><strong>125</strong><span>оценок</span></div></div></div></section>
    <section class="lx-section lx-break" id="lx-visit"><div class="lx-head"><div><h2>Визит</h2><p>Всё нужное перед приездом</p></div></div><div class="lx-visitcard"><div class="lx-vrow"><svg viewBox="0 0 24 24"><path d="M12 21s6-5.4 6-11a6 6 0 1 0-12 0c0 5.6 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></svg><div><strong>Адрес</strong><span>Ивантеевка, ул. Победы, 16</span></div></div><div class="lx-vrow"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/></svg><div><strong>График</strong><span>Вт–Вс 10:00–20:00 · Понедельник — выходной</span></div></div><div class="lx-vrow"><svg viewBox="0 0 24 24"><path d="M7 4h3l1.2 4-2 1.4a15 15 0 0 0 5.4 5.4l1.4-2L20 14v3c0 1.1-.9 2-2 2C10.8 19 5 13.2 5 6c0-1.1.9-2 2-2Z"/></svg><div><strong>Телефон</strong><span>+7 916 355-22-22</span></div></div><div class="lx-vactions"><a class="lx-vbtn" href="${YANDEX}" target="_blank">Маршрут</a><a class="lx-vbtn black" href="tel:${PHONE}">Позвонить</a></div></div></section>
    <footer class="lx-footer"><strong>STLuxe</strong>Цифровой офис на TANEM</footer>
    <div class="lx-bookbar" id="lxBookbar"><div class="lx-bookcopy"><strong>Доступно 70+ услуг</strong><span>Выберите услугу и удобное время</span></div><button data-book>Забронировать</button></div>
    <div class="lx-light" id="lxLight"><div class="lx-lighttop"><span class="lx-lighttitle">Галерея STLuxe</span><button class="lx-close" id="lxClose">×</button></div><div class="lx-lighttrack" id="lxLightTrack">${photos.map((p,i)=>`<div class="lx-lightslide"><img src="${p[0]}" alt="${p[2]}"></div>`).join('')}</div><div class="lx-lightcount" id="lxLightCount">1 / ${photos.length}</div></div>
  </main>`;
  document.body.appendChild(root);

  const state=document.getElementById('lxState'), hoursText=document.getElementById('lxHoursText');
  function updateHours(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Moscow',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const day=parts.find(x=>x.type==='weekday').value;const h=+parts.find(x=>x.type==='hour').value;const m=+parts.find(x=>x.type==='minute').value;const mins=h*60+m;const open=day!=='Mon'&&mins>=600&&mins<1200;state.textContent=open?'Открыто':'Закрыто';state.className='lx-state '+(open?'open':'closed');hoursText.textContent=day==='Mon'?'— откроется во вторник в 10:00':open?'— сегодня до 20:00':mins<600?'— откроется сегодня в 10:00':'— откроется завтра в 10:00';}
  updateHours();

  const track=document.getElementById('lxTrack'),count=document.getElementById('lxCount');track.addEventListener('scroll',()=>{const i=Math.round(track.scrollLeft/track.clientWidth);count.textContent=`${i+1}/${photos.length}`},{passive:true});
  function openGallery(i=0){const l=document.getElementById('lxLight'),t=document.getElementById('lxLightTrack');l.classList.add('open');document.body.style.overflow='hidden';requestAnimationFrame(()=>t.scrollLeft=i*t.clientWidth)}
  document.querySelectorAll('.lx-slide,.lx-photo').forEach(b=>b.addEventListener('click',()=>openGallery(+b.dataset.i||0)));document.getElementById('lxOpenGallery').onclick=()=>openGallery(0);document.getElementById('lxClose').onclick=()=>{document.getElementById('lxLight').classList.remove('open');document.body.style.overflow=''};document.getElementById('lxLightTrack').addEventListener('scroll',e=>{const t=e.currentTarget,i=Math.round(t.scrollLeft/t.clientWidth);document.getElementById('lxLightCount').textContent=`${i+1} / ${photos.length}`},{passive:true});

  document.getElementById('lxToWorks').onclick=()=>document.getElementById('lx-portfolio').scrollIntoView({behavior:'smooth'});document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>location.href=`tel:${PHONE}`);
  document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.go).scrollIntoView({behavior:'smooth'}));
  const filterBtns=[...document.querySelectorAll('.lx-filter')];filterBtns.forEach(b=>b.onclick=()=>{filterBtns.forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.lx-photo').forEach(p=>p.hidden=b.dataset.cat!=='all'&&p.dataset.cat!==b.dataset.cat)});

  let serviceCat='all',expanded=false;const list=document.getElementById('lxServices'),more=document.getElementById('lxMore');
  function renderServices(){const items=services.filter(s=>serviceCat==='all'||s[0]===serviceCat);const shown=expanded?items:items.slice(0,6);list.innerHTML=shown.map(s=>`<article class="lx-service"><div class="lx-sname">${s[1]}</div><div class="lx-smeta"><div class="lx-sprice">${s[2]}${s[3]?`<span class="lx-duration">${s[3]}</span>`:''}</div><button class="lx-reserve">Забронировать</button></div></article>`).join('');list.querySelectorAll('.lx-reserve').forEach(b=>b.onclick=()=>location.href=`tel:${PHONE}`);more.style.display=items.length>6?'block':'none';more.textContent=expanded?'Свернуть':'Посмотреть ещё';}
  renderServices();more.onclick=()=>{expanded=!expanded;renderServices()};const tabs=[...document.querySelectorAll('[data-scat]')];tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));b.classList.add('active');serviceCat=b.dataset.scat;expanded=false;renderServices()});

  const navBtns=[...document.querySelectorAll('[data-go]')],sections=navBtns.map(b=>document.getElementById(b.dataset.go));const bookbar=document.getElementById('lxBookbar'),hero=document.getElementById('lxHero'),about=document.getElementById('lx-about');
  function onScroll(){const y=scrollY;const heroBottom=hero.offsetTop+hero.offsetHeight;const hideAt=about.offsetTop-innerHeight*.72;bookbar.classList.toggle('show',y>heroBottom-20&&y<hideAt);let active=0;sections.forEach((s,i)=>{if(s.getBoundingClientRect().top<=95)active=i});navBtns.forEach((b,i)=>b.classList.toggle('active',i===active));}
  addEventListener('scroll',onScroll,{passive:true});onScroll();
})();