from pathlib import Path
import re

p=Path('mobile-stluxe-final-v22.js')
s=p.read_text()
orig=s

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'missing marker: {label}')
    s=s.replace(old,new,1)

# Hero geometry and manual media behavior styles
rep("#stluxe-tanem-v13 .tn13-hero{height:706px!important;min-height:706px!important;padding:0!important;background:#f8f4ee!important;position:relative!important;overflow:hidden!important}",
    "#stluxe-tanem-v13 .tn13-hero{height:738px!important;min-height:738px!important;padding:0!important;background:#f8f4ee!important;position:relative!important;overflow:hidden!important}#stluxe-tanem-v13>.tn13-footer{display:none!important}", 'hero height/footer')
rep(".tn22-media{position:absolute;top:52px;left:0;right:0;height:372px;overflow:hidden;background:#eee;border:0;padding:0}",
    ".tn22-media{position:absolute;top:52px;left:0;right:0;height:372px;overflow:hidden;background:#eee;border:0;padding:0;touch-action:pan-y}", 'hero media')
rep(".tn22-card{position:absolute;z-index:8;top:343px;left:21px;right:21px;height:292px;padding:20px;border-radius:13px;background:rgba(249,246,241,.985);box-shadow:0 10px 28px rgba(47,37,31,.08);text-align:center}",
    ".tn22-card{position:absolute;z-index:8;top:343px;left:21px;right:21px;height:314px;padding:20px;border-radius:13px;background:rgba(249,246,241,.985);box-shadow:0 10px 28px rgba(47,37,31,.08);text-align:center}", 'hero card')
rep(".tn22-worklink{display:inline-flex;align-items:center;gap:7px;margin-top:15px;color:#25211f;text-decoration:none;font:500 12.5px/1 'Manrope',Arial,sans-serif}",
    ".tn22-worklink{display:inline-flex;align-items:center;gap:7px;margin-top:12px;color:#25211f;text-decoration:none;font:500 12.5px/1 'Manrope',Arial,sans-serif}", 'work link')
rep(".tn22-ticker{position:absolute;z-index:7;left:0;right:0;top:647px;height:37px", ".tn22-ticker{position:absolute;z-index:7;left:0;right:0;top:682px;height:37px", 'ticker')

# Sticky section nav CSS
sticky_css="""
.tn23-section-nav{position:sticky;z-index:70;top:0;height:48px;display:flex;align-items:stretch;overflow-x:auto;scrollbar-width:none;background:rgba(255,255,255,.98);border-bottom:1px solid #e7e4e1;box-shadow:0 3px 12px rgba(30,25,22,.035)}.tn23-section-nav::-webkit-scrollbar{display:none}.tn23-section-nav button{position:relative;flex:0 0 auto;min-width:92px;padding:0 14px;border:0;background:transparent;color:#8a8886;font:500 12px/1 'Manrope',Arial,sans-serif;white-space:nowrap}.tn23-section-nav button.active{color:#151412}.tn23-section-nav button.active:after{content:'';position:absolute;left:18px;right:18px;bottom:0;height:3px;border-radius:3px 3px 0 0;background:#111}
"""
rep("#tn13Portfolio{margin:0!important", sticky_css+"\n#tn13Portfolio{margin:0!important", 'sticky nav css')

# Portfolio: no hole, seven images fill four visual rows (first spans two rows)
rep(".tn22-photo:nth-child(1){grid-row:span 2}.tn22-photo:nth-child(6){grid-column:span 2;height:150px}",
    ".tn22-photo:nth-child(1){grid-row:span 2}", 'portfolio layout')

# Services styles: warmer background, pill category rail, fixed menu button, separate cards
service_css="""#tn13Services{margin:0!important;padding:0!important;background:#5a504a!important;color:#f5eee7!important;overflow:hidden!important}.tn22-services{padding:44px 18px 42px}.tn22-services .tn22-kicker{color:#d5cac1}.tn22-services h2{font-size:42px;color:#fff;white-space:nowrap}.tn23-tabbar{position:relative;margin-top:28px;padding-right:54px}.tn22-tabs{display:flex;gap:8px;overflow-x:auto;scrollbar-width:none;padding:0 2px}.tn22-tabs::-webkit-scrollbar{display:none}.tn22-tab{flex:0 0 auto;height:46px;padding:0 18px;border:1px solid rgba(255,255,255,.2);border-radius:999px;background:#f7f5f2;color:#272321;font:500 11.5px/1 'Manrope',Arial,sans-serif;white-space:nowrap}.tn22-tab.active{background:#111;color:#fff!important;border-color:#111}.tn23-cat-menu{position:absolute;z-index:4;right:0;top:0;width:46px;height:46px;border:1px solid rgba(40,34,31,.16);border-radius:50%;background:#fff;color:#171513;box-shadow:0 6px 18px rgba(30,24,21,.16);display:grid;place-items:center}.tn23-cat-menu svg{width:22px;height:22px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round}.tn23-cat-pop{position:absolute;z-index:5;right:0;top:53px;width:176px;padding:7px;border:1px solid rgba(44,36,32,.14);border-radius:14px;background:#faf8f5;box-shadow:0 14px 36px rgba(34,27,24,.22);display:none}.tn23-cat-pop.open{display:grid}.tn23-cat-pop button{height:38px;border:0;border-radius:9px;background:transparent;color:#292522;text-align:left;padding:0 10px;font:500 11px/1 'Manrope',Arial,sans-serif}.tn23-cat-pop button.active{background:#111;color:#fff!important}.tn22-service-list{display:grid;gap:10px;margin-top:20px;border:0}.tn22-service{display:grid;grid-template-columns:minmax(0,1fr) 90px;gap:12px;padding:14px;border:1px solid rgba(255,255,255,.14);border-radius:14px;background:rgba(255,255,255,.055);align-items:center}.tn22-service-name{font:500 16px/1.18 'Cormorant Garamond',Georgia,serif;color:#fff}.tn22-service-desc{margin-top:7px;font:400 10.5px/1.48 'Manrope',Arial,sans-serif;color:#d2c7bf}.tn22-service-desc .clip{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.tn22-more{border:0;background:none;color:#f0d0ad;padding:0 0 0 4px;font-size:10px;text-decoration:underline;text-underline-offset:2px}.tn22-service-side{text-align:right;min-width:0}.tn22-price{font:500 15px/1 'Cormorant Garamond',Georgia,serif;color:#f0d0ad}.tn22-book-mini{width:88px;height:32px;margin-top:9px;padding:0 3px;border:1px solid rgba(241,220,197,.38);border-radius:8px;background:#171411;color:#fff!important;font:500 9px/1 'Manrope',Arial,sans-serif;white-space:nowrap}.tn22-show-services{width:100%;height:46px;margin-top:18px;border:1px solid rgba(241,220,197,.3);border-radius:11px;background:rgba(255,255,255,.04);color:#fff;font:500 11px/1 'Manrope',Arial,sans-serif}"""
s,n=re.subn(r"#tn13Services\{.*?\.tn22-show-services\{.*?\}\n\n#tn13Team",service_css+"\n\n#tn13Team",s,count=1,flags=re.S)
if n!=1: raise SystemExit('services css block not replaced')

# Review tracks: JS-driven, slower and draggable
s,n=re.subn(r"\.tn22-track\{display:flex;.*?@keyframes tn22ReviewsLeft\{.*?\}",
".tn22-track{display:flex;width:max-content;gap:10px;padding-left:10px;will-change:transform;transform:translate3d(0,0,0);touch-action:pan-y;cursor:grab;user-select:none}.tn22-track.dragging{cursor:grabbing}",s,count=1,flags=re.S)
if n!=1: raise SystemExit('reviews animation css not replaced')

# Status border and clock icon
rep(".tn22-status{padding:8px 10px;border-radius:999px;font:600 10px/1 'Manrope',Arial,sans-serif}",
    ".tn22-status{display:inline-flex;align-items:center;gap:7px;padding:8px 10px;border:1px solid #201c19;border-radius:999px;font:600 10px/1 'Manrope',Arial,sans-serif}.tn22-status svg{width:15px;height:15px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}", 'status css')

# Gallery is 2 columns for every category + empty state
rep(".tn22-gallery-grid.salon{grid-template-columns:1fr}", ".tn22-gallery-grid.salon{grid-template-columns:1fr 1fr}", 'gallery salon grid')
rep(".tn22-gallery-grid.salon .tn22-gallery-tile{aspect-ratio:1.35/1}", ".tn22-gallery-grid.salon .tn22-gallery-tile{aspect-ratio:1/1}.tn23-gallery-empty{grid-column:1/-1;padding:54px 10px;text-align:center;color:#847a73;font:400 13px/1.5 'Manrope',Arial,sans-serif}", 'gallery salon ratio')

# Viewer like Nonna/Tahmina: no expand button, clean frame and footer
viewer_css=""".tn22-viewer{position:fixed;z-index:180;inset:0;display:none;align-items:center;justify-content:center;padding:22px;background:rgba(27,20,20,.9);backdrop-filter:blur(9px)}.tn22-viewer.open{display:flex}.tn22-viewer-frame{position:relative;width:min(100%,520px);height:min(82dvh,720px);background:transparent;overflow:visible;touch-action:none}.tn23-viewer-hint{position:absolute;z-index:4;top:-42px;left:0;color:rgba(255,255,255,.65);font:400 10px/1 'Manrope',Arial,sans-serif}.tn22-viewer-img{position:absolute;left:0;right:0;top:50%;width:100%;max-height:72%;transform:translateY(-50%);object-fit:contain;border-radius:10px;background:#151312;box-shadow:0 18px 54px rgba(0,0,0,.28);transform-origin:center center}.tn22-viewer-top{position:absolute;z-index:5;top:-52px;left:0;right:0;display:flex;justify-content:flex-end}.tn22-viewer-actions{display:flex}.tn22-vbtn{width:42px;height:42px;border:1px solid rgba(255,255,255,.22);border-radius:50%;background:rgba(255,255,255,.08);color:#fff!important;font-size:22px}.tn22-navbtn{position:absolute;z-index:5;top:50%;transform:translateY(-50%);width:30px;height:52px;border:0;background:transparent;color:#fff!important;font-size:35px;line-height:1}.tn22-prev{left:-5px}.tn22-next{right:-5px}.tn22-navbtn[hidden]{display:none!important}.tn23-viewer-foot{position:absolute;z-index:5;left:0;right:0;bottom:-34px;display:flex;align-items:center;justify-content:space-between;color:rgba(255,255,255,.68);font:400 10px/1 'Manrope',Arial,sans-serif}.tn22-viewer-count{font:500 10px/1 'Manrope',Arial,sans-serif;color:#fff}"""
s,n=re.subn(r"\.tn22-viewer\{.*?\.tn22-navbtn\[hidden\]\{display:none!important\}",viewer_css,s,count=1,flags=re.S)
if n!=1: raise SystemExit('viewer css block not replaced')

# Master page continuous profile sections
master_extra=""".tn23-master-stack{display:grid;gap:12px;margin-top:22px}.tn23-master-section{padding:17px;border:1px solid rgba(61,49,43,.1);border-radius:14px;background:rgba(255,255,255,.62)}.tn23-master-section h3{margin:0 0 11px;font:500 27px/1 'Cormorant Garamond',Georgia,serif}.tn23-master-empty{margin:0;color:#82776f;font:400 12px/1.5 'Manrope',Arial,sans-serif}.tn23-master-review{padding-top:10px;margin-top:10px;border-top:1px solid rgba(61,49,43,.08)}.tn23-master-review:first-of-type{padding-top:0;margin-top:0;border-top:0}.tn23-master-review strong{font:500 16px/1 'Cormorant Garamond',Georgia,serif}.tn23-master-review p{margin:6px 0 0;color:#514943;font:400 11px/1.5 'Manrope',Arial,sans-serif}"""
rep(".tn22-master-book{position:fixed",master_extra+".tn22-master-book{position:fixed",'master extra css')

# Gallery lashes category (no invented photos)
rep("'Волосы':[\n {src:'assets/images/hair-style.webp',alt:'Работа с волосами STLuxe'},\n {src:'assets/images/hair-style.webp',alt:'Укладка волос STLuxe'}\n]};",
"'Волосы':[\n {src:'assets/images/hair-style.webp',alt:'Работа с волосами STLuxe'},\n {src:'assets/images/hair-style.webp',alt:'Укладка волос STLuxe'}\n],\n'Ресницы':[]};",'lashes category')

# No hero autoplay. Manual swipe changes photo; tap opens salon gallery.
old_auto="let slide=0; const slides=[...hero.querySelectorAll('.tn22-slide')],dots=[...hero.querySelectorAll('.tn22-dots i')]; setInterval(()=>{slide=(slide+1)%slides.length;slides.forEach((x,i)=>x.classList.toggle('active',i===slide));dots.forEach((x,i)=>x.classList.toggle('active',i===slide));},4800);"
new_auto="""let slide=0; const slides=[...hero.querySelectorAll('.tn22-slide')],dots=[...hero.querySelectorAll('.tn22-dots i')];
function setHeroSlide(i){slide=(i+slides.length)%slides.length;slides.forEach((x,j)=>x.classList.toggle('active',j===slide));dots.forEach((x,j)=>x.classList.toggle('active',j===slide));}
const heroMedia=hero.querySelector('.tn22-media');let heroStartX=0,heroMoved=false;
heroMedia.addEventListener('pointerdown',e=>{heroStartX=e.clientX;heroMoved=false});
heroMedia.addEventListener('pointermove',e=>{if(Math.abs(e.clientX-heroStartX)>12)heroMoved=true});
heroMedia.addEventListener('pointerup',e=>{const dx=e.clientX-heroStartX;if(Math.abs(dx)>42){setHeroSlide(slide+(dx<0?1:-1));return}if(!heroMoved)openGallery('Салон')});"""
rep(old_auto,new_auto,'hero autoplay')

# Viewer markup and behavior
old_viewer="const viewer=document.createElement('div');viewer.className='tn22-viewer';viewer.innerHTML=`<div class=\"tn22-viewer-frame\"><div class=\"tn22-viewer-top\"><span class=\"tn22-viewer-count\">1 / 1</span><div class=\"tn22-viewer-actions\"><button class=\"tn22-vbtn tn22-expand\" type=\"button\" aria-label=\"Расширить\">↗</button><button class=\"tn22-vbtn tn22-view-close\" type=\"button\" aria-label=\"Закрыть\">×</button></div></div><img class=\"tn22-viewer-img\" alt=\"\"><button class=\"tn22-navbtn tn22-prev\" type=\"button\">‹</button><button class=\"tn22-navbtn tn22-next\" type=\"button\">›</button></div>`;root.appendChild(viewer);"
new_viewer="const viewer=document.createElement('div');viewer.className='tn22-viewer';viewer.innerHTML=`<div class=\"tn22-viewer-frame\"><div class=\"tn23-viewer-hint\">Разведите двумя пальцами, чтобы увеличить</div><div class=\"tn22-viewer-top\"><div class=\"tn22-viewer-actions\"><button class=\"tn22-vbtn tn22-view-close\" type=\"button\" aria-label=\"Закрыть\">×</button></div></div><img class=\"tn22-viewer-img\" alt=\"\"><button class=\"tn22-navbtn tn22-prev\" type=\"button\">‹</button><button class=\"tn22-navbtn tn22-next\" type=\"button\">›</button><div class=\"tn23-viewer-foot\"><span class=\"tn23-viewer-label\">Фото STLuxe</span><span class=\"tn22-viewer-count\">01 / 01</span></div></div>`;root.appendChild(viewer);"
rep(old_viewer,new_viewer,'viewer markup')
rep("vCount.textContent=`${viewerIndex+1} / ${viewerItems.length}`;", "vCount.textContent=`${String(viewerIndex+1).padStart(2,'0')} / ${String(viewerItems.length).padStart(2,'0')}`;vImg.style.transform='translateY(-50%) scale(1)';viewerScale=1;", 'viewer count')
rep("function closeViewer(){viewer.classList.remove('open');vFrame.classList.remove('zoom');if(!$('#tn13Gallery').classList.contains('open')&&!masterPage.classList.contains('open'))document.body.style.overflow=''}", "function closeViewer(){viewer.classList.remove('open');vImg.style.transform='translateY(-50%) scale(1)';viewerScale=1;if(!$('#tn13Gallery').classList.contains('open')&&!masterPage.classList.contains('open'))document.body.style.overflow=''}", 'viewer close')
old_events="vPrev.onclick=()=>{viewerIndex=(viewerIndex-1+viewerItems.length)%viewerItems.length;paintViewer()};vNext.onclick=()=>{viewerIndex=(viewerIndex+1)%viewerItems.length;paintViewer()};viewer.querySelector('.tn22-expand').onclick=()=>vFrame.classList.toggle('zoom');viewer.querySelector('.tn22-view-close').onclick=closeViewer;viewer.addEventListener('click',e=>{if(e.target===viewer)closeViewer()});let sx=0;vFrame.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});vFrame.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45&&viewerItems.length>1)(dx<0?vNext:vPrev).click()},{passive:true});"
new_events="""vPrev.onclick=()=>{viewerIndex=(viewerIndex-1+viewerItems.length)%viewerItems.length;paintViewer()};vNext.onclick=()=>{viewerIndex=(viewerIndex+1)%viewerItems.length;paintViewer()};viewer.querySelector('.tn22-view-close').onclick=closeViewer;viewer.addEventListener('click',e=>{if(e.target===viewer)closeViewer()});let sx=0,viewerScale=1,pinchStart=0;
const pinchDist=e=>Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);
vFrame.addEventListener('touchstart',e=>{if(e.touches.length===2){pinchStart=pinchDist(e)}else if(e.touches.length===1){sx=e.touches[0].clientX}},{passive:true});
vFrame.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinchStart){e.preventDefault();viewerScale=Math.max(1,Math.min(3,pinchDist(e)/pinchStart));vImg.style.transform=`translateY(-50%) scale(${viewerScale})`}},{passive:false});
vFrame.addEventListener('touchend',e=>{if(e.changedTouches.length===1&&viewerScale===1&&viewerItems.length>1){const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)(dx<0?vNext:vPrev).click()}if(e.touches.length<2)pinchStart=0},{passive:true});"""
rep(old_events,new_events,'viewer events')

# Gallery render includes empty category
old_rg="function renderGallery(){const items=GALLERY[galleryCat]||[];gallery.innerHTML=`<div class=\"tn22-gallery\"><div class=\"tn22-gallery-top\"><button class=\"tn22-gallery-back\" type=\"button\">←</button><div class=\"tn22-gallery-title\"><strong>Галерея</strong><span>STLuxe</span></div><div></div></div><div class=\"tn22-gallery-tabs\">${Object.keys(GALLERY).map(c=>`<button class=\"tn22-gallery-tab${c===galleryCat?' active':''}\" type=\"button\" data-gcat=\"${c}\">${c}</button>`).join('')}</div><div class=\"tn22-gallery-grid${galleryCat==='Салон'?' salon':''}\">${items.map((x,i)=>`<button class=\"tn22-gallery-tile\" type=\"button\" data-gi=\"${i}\"><img src=\"${x.src}\" alt=\"${x.alt}\"></button>`).join('')}</div></div>`;gallery.querySelector('.tn22-gallery-back').onclick=closeGallery;gallery.querySelectorAll('[data-gcat]').forEach(b=>b.onclick=()=>{galleryCat=b.dataset.gcat;renderGallery()});gallery.querySelectorAll('[data-gi]').forEach(b=>b.onclick=()=>openViewer(items,+b.dataset.gi));}"
new_rg="function renderGallery(){const items=GALLERY[galleryCat]||[];gallery.innerHTML=`<div class=\"tn22-gallery\"><div class=\"tn22-gallery-top\"><button class=\"tn22-gallery-back\" type=\"button\">←</button><div class=\"tn22-gallery-title\"><strong>Галерея</strong><span>STLuxe</span></div><div></div></div><div class=\"tn22-gallery-tabs\">${Object.keys(GALLERY).map(c=>`<button class=\"tn22-gallery-tab${c===galleryCat?' active':''}\" type=\"button\" data-gcat=\"${c}\">${c}</button>`).join('')}</div><div class=\"tn22-gallery-grid${galleryCat==='Салон'?' salon':''}\">${items.length?items.map((x,i)=>`<button class=\"tn22-gallery-tile\" type=\"button\" data-gi=\"${i}\"><img src=\"${x.src}\" alt=\"${x.alt}\"></button>`).join(''):'<div class=\"tn23-gallery-empty\">Фото ресниц пока не добавлены</div>'}</div></div>`;gallery.querySelector('.tn22-gallery-back').onclick=closeGallery;gallery.querySelectorAll('[data-gcat]').forEach(b=>b.onclick=()=>{galleryCat=b.dataset.gcat;renderGallery()});gallery.querySelectorAll('[data-gi]').forEach(b=>b.onclick=()=>openViewer(items,+b.dataset.gi));}"
rep(old_rg,new_rg,'gallery render')
# Remove old direct media click (manual handler above owns it)
rep("hero.querySelector('.tn22-media').addEventListener('click',()=>openGallery('Салон'));", "", 'old hero gallery click')

# Section nav after hero
nav_js="""
const sectionNav=document.createElement('nav');sectionNav.className='tn23-section-nav';sectionNav.innerHTML=[['tn13Portfolio','Портфолио'],['tn13Services','Услуги'],['tn13Team','Команда'],['tn13Reviews','Отзывы'],['tn13Visit','Визит']].map((x,i)=>`<button type=\"button\" data-section=\"${x[0]}\" class=\"${i===0?'active':''}\">${x[1]}</button>`).join('');hero.insertAdjacentElement('afterend',sectionNav);sectionNav.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.section)?.scrollIntoView({behavior:'smooth',block:'start'}));const navObs=new IntersectionObserver(entries=>{const hit=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!hit)return;const btn=sectionNav.querySelector(`[data-section=\"${hit.target.id}\"]`);if(!btn)return;sectionNav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===btn));btn.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})},{threshold:[.22,.45,.7],rootMargin:'-48px 0px -45% 0px'});['tn13Portfolio','tn13Services','tn13Team','tn13Reviews','tn13Visit'].forEach(id=>{const el=document.getElementById(id);if(el)navObs.observe(el)});
"""
rep("// PORTFOLIO", nav_js+"\n// PORTFOLIO", 'section nav js')

# Services: manicure first, wrapper with permanent category menu
rep("const serv=$('#tn13Services'); const CATS=['Волосы','Маникюр','Педикюр','Наращивание','Детям','Мужчинам'];let serviceCat='Волосы',serviceExpanded={};",
    "const serv=$('#tn13Services'); const CATS=['Маникюр','Педикюр','Волосы','Наращивание','Детям','Мужчинам'];let serviceCat='Маникюр',serviceExpanded={};", 'service category order')
rep("serv.innerHTML=`<div class=\"tn22-services\"><p class=\"tn22-kicker\">Услуги</p><h2>Наши услуги</h2><div class=\"tn22-tabs\"></div><div class=\"tn22-service-list\"></div><button class=\"tn22-show-services\" type=\"button\"></button></div>`;\nconst tabs=serv.querySelector('.tn22-tabs'),slist=serv.querySelector('.tn22-service-list'),sMore=serv.querySelector('.tn22-show-services');",
    "serv.innerHTML=`<div class=\"tn22-services\"><p class=\"tn22-kicker\">Услуги</p><h2>Наши услуги</h2><div class=\"tn23-tabbar\"><div class=\"tn22-tabs\"></div><button class=\"tn23-cat-menu\" type=\"button\" aria-label=\"Все категории\"><svg viewBox=\"0 0 24 24\"><path d=\"M8 6h12M8 12h12M8 18h12\"/><circle cx=\"4\" cy=\"6\" r=\"1\" fill=\"currentColor\" stroke=\"none\"/><circle cx=\"4\" cy=\"12\" r=\"1\" fill=\"currentColor\" stroke=\"none\"/><circle cx=\"4\" cy=\"18\" r=\"1\" fill=\"currentColor\" stroke=\"none\"/></svg></button><div class=\"tn23-cat-pop\"></div></div><div class=\"tn22-service-list\"></div><button class=\"tn22-show-services\" type=\"button\"></button></div>`;\nconst tabs=serv.querySelector('.tn22-tabs'),slist=serv.querySelector('.tn22-service-list'),sMore=serv.querySelector('.tn22-show-services'),catMenu=serv.querySelector('.tn23-cat-menu'),catPop=serv.querySelector('.tn23-cat-pop');catMenu.onclick=e=>{e.stopPropagation();catPop.classList.toggle('open')};document.addEventListener('pointerdown',e=>{if(!e.target.closest('.tn23-tabbar'))catPop.classList.remove('open')});", 'services markup')
old_rs="function renderServices(){tabs.innerHTML=CATS.map(c=>`<button class=\"tn22-tab${c===serviceCat?' active':''}\" type=\"button\" data-scat=\"${c}\">${c}</button>`).join('');tabs.querySelectorAll('[data-scat]').forEach(b=>b.onclick=()=>{serviceCat=b.dataset.scat;renderServices();requestAnimationFrame(()=>b.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'}))});const arr=SERVICES.filter(s=>s.cat===serviceCat),expanded=!!serviceExpanded[serviceCat],shown=expanded?arr:arr.slice(0,7);slist.innerHTML=shown.map(serviceRow).join('');bindDesc();sMore.hidden=arr.length<=7||expanded;sMore.textContent=`Показать все услуги · ${arr.length}`;sMore.onclick=()=>{serviceExpanded[serviceCat]=true;renderServices()}}"
new_rs="function renderServices(){tabs.innerHTML=CATS.map(c=>`<button class=\"tn22-tab${c===serviceCat?' active':''}\" type=\"button\" data-scat=\"${c}\">${c}</button>`).join('');catPop.innerHTML=CATS.map(c=>`<button class=\"${c===serviceCat?'active':''}\" type=\"button\" data-popcat=\"${c}\">${c}</button>`).join('');const choose=c=>{serviceCat=c;catPop.classList.remove('open');renderServices();requestAnimationFrame(()=>tabs.querySelector(`[data-scat=\"${c}\"]`)?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'}))};tabs.querySelectorAll('[data-scat]').forEach(b=>b.onclick=()=>choose(b.dataset.scat));catPop.querySelectorAll('[data-popcat]').forEach(b=>b.onclick=()=>choose(b.dataset.popcat));const arr=SERVICES.filter(s=>s.cat===serviceCat),expanded=!!serviceExpanded[serviceCat],shown=expanded?arr:arr.slice(0,7);slist.innerHTML=shown.map(serviceRow).join('');bindDesc();sMore.hidden=arr.length<=7||expanded;sMore.textContent=`Показать все услуги · ${arr.length}`;sMore.onclick=()=>{serviceExpanded[serviceCat]=true;renderServices()}}"
rep(old_rs,new_rs,'render services')

# Master profile: all sections vertically, no tabs
start=s.find("function masterReviews(m)")
end=s.find("team.querySelectorAll('[data-mid]')",start)
if start<0 or end<0: raise SystemExit('master function bounds missing')
new_master="""function masterReviews(m){return REVIEW_DATA.filter(r=>m.reviewNames.includes(r[0]));}
function openMaster(id){currentMaster=MASTERS.find(m=>m.id===id);if(!currentMaster)return;const rs=masterReviews(currentMaster);const b=masterPage.querySelector('.tn22-master-body');const empty='<p class=\"tn23-master-empty\">Информация пока не добавлена.</p>';b.innerHTML=`<div class=\"tn22-profile\"><div class=\"tn22-profile-circle\"><span>${currentMaster.initial}</span></div><h1>${currentMaster.name}</h1><div class=\"tn22-profile-role\">${currentMaster.role} · ${currentMaster.detail}</div><div class=\"tn22-salon-rating\"><b>★</b> 4,9 <span>рейтинг салона</span></div></div><div class=\"tn23-master-stack\"><section class=\"tn23-master-section\"><h3>О мастере</h3><p class=\"tn22-master-about\" style=\"text-align:left;margin:0;max-width:none\">${currentMaster.about||'Информация пока не добавлена.'}</p></section><section class=\"tn23-master-section\"><h3>Услуги</h3>${empty}</section><section class=\"tn23-master-section\"><h3>Портфолио</h3>${empty}</section><section class=\"tn23-master-section\"><h3>Отзывы</h3>${rs.length?rs.map(r=>`<div class=\"tn23-master-review\"><strong>${r[0]}</strong><p>${r[1]}</p></div>`).join(''):empty}</section></div>`;teamSheet.classList.remove('open');masterPage.classList.add('open');document.body.style.overflow='hidden'}
"""
s=s[:start]+new_master+s[end:]

# Reviews: independent slow RAF tracks, drag each track, resume after 800ms
old_review="reviews.querySelectorAll('[data-track]').forEach(t=>{let timer;t.addEventListener('pointerdown',()=>{clearTimeout(timer);t.classList.add('paused')});const resume=()=>{clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('paused'),500)};t.addEventListener('pointerup',resume);t.addEventListener('pointercancel',resume);t.addEventListener('pointerleave',resume)});"
new_review="""reviews.querySelectorAll('[data-track]').forEach((t,i)=>{let offset=0,half=0,drag=false,startX=0,startOffset=0,moved=false,resumeAt=0,last=performance.now();const dir=i===1?-1:1,speed=12;const measure=()=>{half=t.scrollWidth/2;if(i!==1&&offset===0)offset=-half};requestAnimationFrame(measure);window.addEventListener('resize',measure,{passive:true});const wrap=()=>{if(!half)return;if(offset>=0)offset=-half;if(offset<=-half)offset=0};t.addEventListener('pointerdown',e=>{drag=true;moved=false;resumeAt=Infinity;startX=e.clientX;startOffset=offset;t.classList.add('dragging');try{t.setPointerCapture(e.pointerId)}catch(_){}});t.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-startX;if(Math.abs(dx)>3)moved=true;offset=startOffset+dx;wrap();t.style.transform=`translate3d(${offset}px,0,0)`});const release=()=>{if(!drag)return;drag=false;t.classList.remove('dragging');resumeAt=performance.now()+800};t.addEventListener('pointerup',release);t.addEventListener('pointercancel',release);t.addEventListener('click',e=>{if(moved){e.preventDefault();e.stopPropagation()}},true);const tick=now=>{const dt=Math.min(50,now-last);last=now;if(!drag&&now>=resumeAt){offset+=dir*speed*dt/1000;wrap();t.style.transform=`translate3d(${offset}px,0,0)`}requestAnimationFrame(tick)};requestAnimationFrame(tick)});"""
rep(old_review,new_review,'reviews interaction')

# Contact status: black border + clock illustration on the right
rep("<span class=\"tn22-status\" id=\"tn22Status\"></span>", "<span class=\"tn22-status\" id=\"tn22Status\"><span class=\"tn22-status-text\"></span>${clock}</span>", 'status markup')
old_status="if(open){el.textContent='Открыто до 20:00';el.className='tn22-status open'}else{el.textContent=monday?'Закрыто до вт 10:00':'Закрыто до 10:00';el.className='tn22-status closed'}"
new_status="const txt=el.querySelector('.tn22-status-text');if(open){txt.textContent='Открыто до 20:00';el.className='tn22-status open'}else{txt.textContent=monday?'Закрыто до вт 10:00':'Закрыто до 10:00';el.className='tn22-status closed'}"
rep(old_status,new_status,'status function')

# Bump marker inside file for audit
if "STLUXE_V23_REFINED" not in s:
    s=s.replace("'use strict';","'use strict';\nconst STLUXE_V23_REFINED=true;",1)

if s==orig: raise SystemExit('no changes')
p.write_text(s)
print('refined', len(orig), '->', len(s))
